name: First Workflow

on: 
  push:
    branches:
      -main 

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/ checkout@v2

      - name: Display a message
        run: echo "Hello, Github Actions!"